# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/user/application_security/sast/#available-cicd-variables
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure/
# Dependency Scanning customization: https://docs.gitlab.com/user/application_security/dependency_scanning/dependency_scanning_sbom/#customizing-analyzer-behavior
# Container Scanning customization: https://docs.gitlab.com/user/application_security/container_scanning/#customizing-analyzer-behavior
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ci/variables/#cicd-variable-precedence
stages:
- test
- secret-detection
- code-test
- build

##########################
# Rules - Main
##########################

.web_manual_trigger: &web_trigger
  if: $CI_PIPELINE_SOURCE == "web"

.auto_file_watch_trigger: &file_watch_trigger
  if: $CI_PIPELINE_SOURCE == "push"
  changes:
    - Dockerfile
    - "src/main/java/com/tcyao/nid/**/*"

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
variables:
  SECRET_DETECTION_ENABLED: 'true'
secret_detection:
  stage: secret-detection

spring-test:
  stage: code-test
  rules:
    - *web_trigger
    - *file_watch_trigger
  script:
    - mvn test

image-build:
  stage: build
  rules:
    - *web_trigger
    - *file_watch_trigger
  variables:
    IMAGE_NAME: "$CI_REGISTRY_IMAGE:latest"
  script:
    - |
      docker build -t "$IMAGE_NAME" .
      docker push "$IMAGE_NAME"